spring.application.name=SwiftPay
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5432/swiftpay
spring.datasource.username=postgres
spring.datasource.password=231728
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.main.allow-circular-references=true


# Access Token validity - 15 minutes(900000) - 1 minute(60000)
jwt.token.expiration=900000

# Refresh Token validity handled separately in RefreshTokenService (7 days)

# To stop Spring default behaviour of Throwing Stack Traces(those long exceptions) use(uncomment) these 2 properties.
#logging.level.org.springframework.web=ERROR
#logging.level.com.swiftpay=ERROR
# One of these is responsible for not showing the spring default behavior like Starting Application at 19.00 ms
# if needed we can also remove these two properties to let spring show behaviour and throw Stack Traces it will still run fine.